name: build
on: [push, workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
  packages: write
jobs:
  build_with_docker:
    runs-on: ubuntu-latest
    name: Build with Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and push with Docker
        run: |
          IMAGE_NAME=docker-localstack
          IMAGE_ID=localstack ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION=v0.0.1
          
          DOCKER_BUILDKIT=1 docker build . --tag docker-localstack

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  build_with_nscloud_to_docker:
    runs-on: ubuntu-latest
    name: Build with Namespace Cloud push to local registry
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and configure Namespace Cloud CLI
        uses: namespacelabs/nscloud-setup@v0.0.1
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Build and push with Namespace Cloud cluster
        run: |
          IMAGE_NAME=nsc-localstack
          IMAGE_ID=localstack ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          VERSION=v0.0.1

          nsc build . --push $IMAGE_ID --tag $VERSION