name: build
on: [push, workflow_dispatch]

permissions:
  id-token: write # This is required for requesting the JWT
jobs:
  build_with_docker:
    runs-on: ubuntu-latest
    name: Build with Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build
        run: |
          DOCKER_BUILDKIT=1 docker build . --tag ns-localstack:v0.0.1

  build_with_nscloud_to_docker:
    runs-on: ubuntu-latest
    name: Build with Namespace Cloud push to local registry
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install and configure Namespace Cloud CLI
        uses: namespacelabs/nscloud-setup@v0.0.1
      - name: Build in Namespace Cloud cluster
        run: |
          nsc build . --push_to_nsc_repo test-repo/ns-localstack --tag v0.0.1,dev